// @ts-nocheck
// Vercel serverless adapter for the TanStack Start SSR / server-function handler.
// The build output at ../dist/server/server.js is generated by `npm run build:vercel`.

import server from '../dist/server/server.js';

export default async function handler(req, res) {
  const url = new URL(req.url || '/', `https://${req.headers.host || 'localhost'}`);

  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      for (const v of value) {
        if (v !== undefined && v !== null) headers.append(key, String(v));
      }
    } else {
      headers.set(key, String(value));
    }
  }

  let body;
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    const buffer = await new Promise((resolve, reject) => {
      const chunks = [];
      req.on('data', (chunk) => chunks.push(chunk));
      req.on('end', () => resolve(Buffer.concat(chunks)));
      req.on('error', reject);
    });
    body = new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
  }

  const request = new Request(url, {
    method: req.method,
    headers,
    body,
  });

  try {
    const response = await server.fetch(request);

    res.statusCode = response.status;
    res.statusMessage = response.statusText;

    response.headers.forEach((value, key) => {
      res.setHeader(key, value);
    });

    if (response.body) {
      const reader = response.body.getReader();
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        res.write(Buffer.from(value));
      }
    }

    res.end();
  } catch (error) {
    console.error('SSR handler error:', error);
    res.statusCode = 500;
    res.end('Internal Server Error');
  }
}
